// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: DeviceNetwork_Final

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x11111B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_arc = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speed_arc, &ui_img_231284188);
    lv_obj_set_width(ui_speed_arc, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_speed_arc, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_speed_arc, 0);
    lv_obj_set_y(ui_speed_arc, 15);
    lv_obj_set_align(ui_speed_arc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speed_arc, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speed_arc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_speed_arc, 200);

    ui_speed_indicator_arrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speed_indicator_arrow, &ui_img_231295465);
    lv_obj_set_width(ui_speed_indicator_arrow, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_speed_indicator_arrow, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_speed_indicator_arrow, 0);
    lv_obj_set_y(ui_speed_indicator_arrow, 18);
    lv_obj_set_align(ui_speed_indicator_arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speed_indicator_arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speed_indicator_arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_speed_indicator_arrow, 64, 68);

    ui_speed_label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speed_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speed_label, 0);
    lv_obj_set_y(ui_speed_label, -17);
    lv_obj_set_align(ui_speed_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_label, "Speed\nkm/h");
    lv_obj_set_style_text_color(ui_speed_label, lv_color_hex(0xCDD6F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_label, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speed_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speed_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speed_value, 0);
    lv_obj_set_y(ui_speed_value, 102);
    lv_obj_set_align(ui_speed_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_value, "20");
    lv_obj_set_style_text_color(ui_speed_value, lv_color_hex(0xCDD6F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speed_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_value, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turn_signal = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_turn_signal);
    lv_obj_set_width(ui_turn_signal, 354);
    lv_obj_set_height(ui_turn_signal, 50);
    lv_obj_set_x(ui_turn_signal, 0);
    lv_obj_set_y(ui_turn_signal, -120);
    lv_obj_set_align(ui_turn_signal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_turn_signal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_turn_signal_left = lv_img_create(ui_turn_signal);
    lv_img_set_src(ui_turn_signal_left, &ui_img_546624313);
    lv_obj_set_width(ui_turn_signal_left, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_turn_signal_left, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_turn_signal_left, -108);
    lv_obj_set_y(ui_turn_signal_left, 0);
    lv_obj_set_align(ui_turn_signal_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turn_signal_left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_turn_signal_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_turn_signal_right = lv_img_create(ui_turn_signal);
    lv_img_set_src(ui_turn_signal_right, &ui_img_465554078);
    lv_obj_set_width(ui_turn_signal_right, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_turn_signal_right, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_turn_signal_right, 110);
    lv_obj_set_y(ui_turn_signal_right, 0);
    lv_obj_set_align(ui_turn_signal_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turn_signal_right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_turn_signal_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_head_light = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_head_light, &ui_img_244846933);
    lv_obj_set_width(ui_head_light, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_head_light, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_head_light, 0);
    lv_obj_set_y(ui_head_light, -120);
    lv_obj_set_align(ui_head_light, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_head_light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_head_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indicator_container = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_indicator_container);
    lv_obj_set_width(ui_indicator_container, 406);
    lv_obj_set_height(ui_indicator_container, 50);
    lv_obj_set_x(ui_indicator_container, 0);
    lv_obj_set_y(ui_indicator_container, 92);
    lv_obj_set_align(ui_indicator_container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_indicator_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_engine_check = lv_img_create(ui_indicator_container);
    lv_img_set_src(ui_engine_check, &ui_img_engine_png);
    lv_obj_set_width(ui_engine_check, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_engine_check, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_engine_check, -160);
    lv_obj_set_y(ui_engine_check, 0);
    lv_obj_set_align(ui_engine_check, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_engine_check, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_engine_check, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_door_check = lv_img_create(ui_indicator_container);
    lv_img_set_src(ui_door_check, &ui_img_left_png);
    lv_obj_set_width(ui_door_check, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_door_check, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_door_check, 160);
    lv_obj_set_y(ui_door_check, 0);
    lv_obj_set_align(ui_door_check, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_door_check, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_door_check, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_airbag_check = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_airbag_check, &ui_img_airbag_png);
    lv_obj_set_width(ui_airbag_check, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_airbag_check, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_airbag_check, 160);
    lv_obj_set_y(ui_airbag_check, 40);
    lv_obj_set_align(ui_airbag_check, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_airbag_check, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_airbag_check, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
