// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: DeviceNetwork_Final

#ifndef _DEVICENETWORK_FINAL_UI_H
#define _DEVICENETWORK_FINAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Indicatorrotation_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_speed_arc;
extern lv_obj_t * ui_speed_indicator_arrow;
extern lv_obj_t * ui_speed_label;
extern lv_obj_t * ui_speed_value;
extern lv_obj_t * ui_turn_signal;
extern lv_obj_t * ui_turn_signal_left;
extern lv_obj_t * ui_turn_signal_right;
extern lv_obj_t * ui_head_light;
extern lv_obj_t * ui_indicator_container;
extern lv_obj_t * ui_engine_check;
extern lv_obj_t * ui_door_check;
extern lv_obj_t * ui_airbag_check;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_231284188);    // assets/gauge (5).png
LV_IMG_DECLARE(ui_img_231295465);    // assets/gauge (8).png
LV_IMG_DECLARE(ui_img_546624313);    // assets/arrows (3).png
LV_IMG_DECLARE(ui_img_465554078);    // assets/arrows (2).png
LV_IMG_DECLARE(ui_img_244846933);    // assets/high-beam (1).png
LV_IMG_DECLARE(ui_img_engine_png);    // assets/engine.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_airbag_png);    // assets/airbag.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
